FROM commic/shopware:base
MAINTAINER Michael Weber <micha.bgl@gmx.de>

ENV SHOPWARE_VERSION=5.2.26

RUN wget -qO /root/shopware.tar.gz https://github.com/shopware/shopware/archive/v$SHOPWARE_VERSION.tar.gz
